"""create links table

Revision ID: 65d309536b27
Revises:
Create Date: 2026-09-24 18:42:42.604912

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "65d309536b27"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column(
            "source_channel",
            sa.Enum("telegram", "desktop", "whatsapp_import", "api", name="source_channel"),
            nullable=False,
        ),
        sa.Column("sender", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("site_name", sa.Text(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum(
                "tweet",
                "instagram",
                "youtube",
                "github_repo",
                "article",
                "product",
                "docs",
                "other",
                name="content_type",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "enriched", "failed", "dead", name="link_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("share_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("shared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_links_normalized_url"), "links", ["normalized_url"], unique=False)
    op.create_index("ix_links_shared_at", "links", ["shared_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_links_shared_at", table_name="links")
    op.drop_index(op.f("ix_links_normalized_url"), table_name="links")
    op.drop_table("links")
    # ### end Alembic commands ###
    # drop_table doesn't remove the Postgres enum types created alongside it.
    for enum_name in ("link_status", "content_type", "source_channel"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
